# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Cuw1ynejZF3W2UgGC-wjLYO4lEM64U2
"""

import torch

class Config:
    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    train_epochs = 20               # 학습 반복 수
    batch_size = 128                # 배치 사이즈
    learning_rate = 0.002           # 학습률 -> 가중치 업데이트 속도
    l2_regularization = 1e-6        # L2 정규화 -> 과적합 방지 용도 / 과적합이 심하면 값을 늘리는 방식으로 수정하길 권함
    learning_rate_decay = 0.99      # 학습률 감소 비율 -> 점진적으로 줄이면서 안정적인 학습으로 유도하기 위함

    drive_base = '/content/drive/MyDrive/IDS/amaxon reviews 2023'
    word2vec_file = f'{drive_base}/glove.6B.50d.txt'
    train_file = f'{drive_base}/dataset/cleaned_Transnet_T2_train.csv'
    valid_file = f'{drive_base}/dataset/cleaned_Transnet_T2__valid.csv'
    test_file = f'{drive_base}/dataset/cleaned_Transnet_T2_test.csv'
    model_file = f'{drive_base}/DeepCONN/model_ver02/best_model.pt'

    review_count = 10               # 최대 리뷰 수 -> 아이템 당 최대 10개의 리뷰 데이터 활용하겠다
    review_length = 40              # 최대 40단어로 제한하겠다
    lowest_review_count = 0
    PAD_WORD = '<UNK>'              # 패딩 단어

    kernel_count = 100              # CNN에서 필터 개수
    kernel_size = 3                 # 필터 크기
    dropout_prob = 0.5              # 드롭아웃의 확률: 과적합 방지를 위한 비활성화 확률
    cnn_out_dim = 50                # CNN 출력 차원