# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XKgWN1s7w994hZKZGafrBLWSPXlESLtb
"""

import torch

class Config:
    def __init__(self):
        self.device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
        self.num_epochs = 10
        self.batch_size = 32
        self.learning_rate = 1e-4
        self.hidden_size = 500
        self.output_size = 1
        self.win_size = 5
        self.channels_local = 200
        self.channels_global = 100

        # 데이터 경로
        self.drive_base = '/content/drive/MyDrive/IDS/amaxon reviews 2023'
        self.train_file = f'{self.drive_base}/dataset/cleaned_Transnet_T2_train.csv'
        self.valid_file = f'{self.drive_base}/dataset/cleaned_Transnet_T2__valid.csv'
        self.test_file = f'{self.drive_base}/dataset/cleaned_Transnet_T2_test.csv'
        self.emb_file = f'{self.drive_base}/combined_word_emb.pkl'
        self.save_path = f'{self.drive_base}/D-attn/model_save3/'

        # 리뷰와 임베딩 관련 설정
        self.input_size = 10000
        self.embed_size = 64
        self.pad = 0