# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gyiaiB9m9lcjzPt3uFrHlKyLEjuWJlfT
"""

# Config 클래스 정의

import torch

class Config:
    def __init__(self):
        self.device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
        self.train_epochs = 15
        self.batch_size = 128
        self.learning_rate = 0.002          # 초기 학습
        self.l2_regularization = 1e-6       # 가중치에 대한 L2 정규화 계
        self.learning_rate_decay = 0.99     # 학습이 진행될수록 학습률을 점진적으로 감소
                                            # 즉, 매 에포크(혹은 특정 단계)마다 학습률이 이전 학습률의 99%로 감소함을 의미합니다.

        self.drive_base = '/content/drive/MyDrive/IDS/amaxon reviews 2023'
        self.train_file = f'{self.drive_base}/Transnet/T2/train.csv'
        self.valid_file = f'{self.drive_base}/Transnet/T2/valid.csv'
        self.test_file = f'{self.drive_base}/Transnet/T2/test.csv'
        self.model_file = f'{self.drive_base}/Transnet/T3/ver02_best_model.pt'
        self.extension = False
        self.user_count = 15225             # preprocess 상에서의 users 값을 기입해야함
        self.item_count = 641                # preprocess 상에서의 items 값을 기입해야함
        self.review_count = 10               # 최대 리뷰 개수 설정
        self.review_length = 80                  # review 최대 길이
        self.lowest_review_count = 1        ## orignal 2
        self.PAD_WORD = '<UNK>'             # review 길이가 부족한 경우 Padding으로 채움
        self.kernel_count = 100              # Kernel 개수
        self.kernel_size = 3                     # Window size
        self.dropout_prob = 0.5              # Dropout rate
        self.cnn_out_dim = 50                    # Latent Feature dimension